services:
  nirvana-proxy:
    image: ghcr.io/aldarondo/nirvana-proxy:latest
    container_name: nirvana-proxy
    restart: unless-stopped
    network_mode: host
    environment:
      - LOG_BODIES=true
      - PROXY_PORT=8443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
